<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
 * @version $Id: innovations.phtml 837 2010-03-16 14:37:24Z yegor256@yahoo.com $
-->
 
<? $this->includeCSS('innovations.css');?>

<?=$this->article->text?>

<?
    // new holder of stories elements
    $articles = Zend_Navigation_Page::factory(array('type'=>'uri'));

    foreach ($this->navigation()->findOneBy('path', $this->article->page)->getPages() as $page) {
        // load news article
        $article = Model_Article::createByLabel($page->path);
            
        // save article for future use
        $page->article = $article;

        // backward chronological order
        $page->order = 1-$article->published->getTimestamp();

        // add the article to the holder, to show later
        $articles->addPage($page);
    }
?>

<? foreach ($articles as $page): ?>
    <p class="innovation">
        <b>
            <a href="<?=$page->href?>">
                <?=$page->article->title?></a></b>, 
        <?=$page->article->description?>
        <br/>
        <span>
            published on <?=$page->article->published->get(Zend_Date::DATE_MEDIUM)?>
        </span>
    </p>
<? endforeach; ?>

