
<p>Creating new project you will immedidately start new PM wobot to work
    with the project.</p>

<?=$this->forma()
    ->addField('text', 'name')
        ->fieldLabel('Name of a new project')
        ->fieldAttrib('size', 15)
        ->fieldAttrib('maxlength', 12)
        ->fieldRequired(true)
    ->addField('submit')
        ->fieldValue('Create new project')
        ->fieldAction($this->root->projectRegistry, 'createNewProject')
    ?>

