<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
-->
 
<?=$this->publish($this->root->supplierRegistry)?>

<h1>Full List of Suppliers</h1>

<?=$this->table()
    ->setSource($this->root->supplierRegistry)
    ->addColumn('email', 'Email')
    ->addColumn('name', 'Full name')
    ->addColumn('skills', 'Skills')
        ->addConverter(
            'callback', 
            create_function('$a', 'return implode(", ", $a);')
        )
    ->addColumn('roles', 'Roles')
        ->addConverter(
            'callback', 
            create_function('$a', 'return implode(", ", $a);')
        )
    ->addColumn('rate', 'Rate')
    ->addColumn('approvedOn', 'Approved On')
    ?>
