<? $this->includeCSS('pages/PMO/Suppliers.css') ?>

<h1>Staff Requests for Suppliers</h1>

<?=$this->table()
    ->setSource($this->root->projectRegistry->getStaffRequests())
    ->addColumn('project', 'Project')
    ->addColumn('role', 'Role')
    ->addColumn('skills', 'Skills required')
    ->addColumn('duration', 'Days')
    ->addColumn('cost', 'Cost')
    ->addColumn('threshold', 'Threshold')
    ->addColumn('response', 'Response')
    ->addOption('response', 'responses/{id}')
    ?>

<!--
    
    $tags = array();
    foreach ($this->registry->wanted as $wanted) {
        $color = hexdec(substr(Model_Colors::BLUE, 1));
        $delta = (1 - $wanted->have / $wanted->required) * 0x2F;
        $color = $color + 0x010000 * $delta + 0x000100 * $delta + $delta;
        $color = sprintf('#%06x', $color);
        $tags[] = new Zend_Tag_Item(array(
            'title' => "<span style='color: {$color};'>" . str_replace(' ', '&nbsp;', $wanted->role) . '</span>',
            'weight' => $wanted->required,
            'url' => $this->link('byRole/' . $wanted->role),
            ));
    }
        
    echo new Zend_Tag_Cloud(array(
        'tags' => $tags,
        'cloudDecorator' => array(
            'decorator' => 'htmlCloud',
            'options' => array(
                'separator' => '',
                'htmlTags' => array(
                    'ul' => array(
                        'class' => 'cloud'
                    )
                )
            )
        ),
        'tagDecorator' => array(
            'decorator' => 'htmlTag',
            'options' => array(
                'fontSizeUnit' => 'em',
                'minFontSize' => 2,
                'maxFontSize' => 4
            )
        )
    ));

-->