<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
-->
 
<? $request = $this->root->projectRegistry->getStaffRequestById($this->segment(-1)) ?>
<? $response = $this->root->supplierRegistry->resolve($request) ?>

<h1>Invite for '<?=$request->role?>' in '<?=$request->project?>'</h1>

<p>Invitation will be sent to:</p>

<ul>
<? foreach ($response as $item): ?>
    <li><?=$item->supplier->email?></li>
<? endforeach; ?>
</ul>

<?=$this->forma()
    ->addBehavior('flash', 'sprintf("Invitation sent")')
    ->addBehavior('redirect')
    ->addField('hidden', 'request')
        ->fieldValue($request)
    ->addField('textarea', 'message')
        ->fieldLabel('Custom message to add', true)
        ->fieldAttrib('cols', 50)
        ->fieldAttrib('rows', 5)
    ->addField('submit', 'send')
        ->fieldValue('Send Invitation')
        ->fieldAttrib('class', 'btn')
        ->fieldAction(array($response, 'invite'))
    ?>
