<? 

    $this->includeCSS('home.css');

    // load News XML file, according to the link in home.xml
    $news = Model_Article::createByLabel((string)$this->article->xml->front->right->news);

    // build a news line
    $newsline = $news->updated->get(Zend_Date::DATE_MEDIUM) . ': ' . cutLongLine($news->description, 200);

    // holder of data
    $front = $this->article->xml->front;

?>

<a href="<?=$this->staticUrl($front->link)?>" title="<?=$this->escape($front->hint)?>">
    <img class="frontimg" src="<?=$this->viewFile($front->image)?>" 
        alt="TechnoParkCorp.com is a Software Development General Contractor" />
</a>

<div class="cln"></div>

<div class="home">
    <table class="headers">
        <tr>
            <td><?=$this->escape($front->left->title)?></td>
            <td><?=$this->escape($front->middle->title)?></td>
            <td><?=$this->escape($front->right->title)?></td>
        </tr>
    </table>
    
    <div style='background-color: #5a6870; height: 1px; width: 100%; margin-top: 4px; color: inherit;'></div>

    <table class="links">
        <tr>
            <td>
                <a href="<?=$this->staticUrl($front->left->item1->attributes()->name)?>"><?=$this->escape($front->left->item1)?></a><br/>
                <a href="<?=$this->staticUrl($front->left->item2->attributes()->name)?>"><?=$this->escape($front->left->item2)?></a><br/>
                <a href="<?=$this->staticUrl($front->left->item3->attributes()->name)?>"><?=$this->escape($front->left->item3)?></a><br/>
            </td><td>
                <a href="<?=$this->staticUrl($front->middle->item1->attributes()->name)?>"><?=$this->escape($front->middle->item1)?></a><br/>
                <a href="<?=$this->staticUrl($front->middle->item2->attributes()->name)?>"><?=$this->escape($front->middle->item2)?></a><br/>
                <a href="<?=$this->staticUrl($front->middle->item3->attributes()->name)?>"><?=$this->escape($front->middle->item3)?></a><br/>
            </td><td style='padding-right: 10px; width: 220px;'>
                <a href="<?=$this->staticUrl($front->right->news)?>"><?=$this->escape($newsline)?></a>
            </td></tr>
    </table>
</div>
