<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
 * @version $Id$
-->
 
<?
    $this->includeCSS('static.css');
    $this->includeCSS('article.css');
?>

<!-- Login line -->
<div class="ll">
    <span style="margin-left: 39px;">Welcome, Dear Visitor</span>
    <?=$this->forma()
        ->setFormAction($this->staticUrl('system/search'))
        ->addField('text', 'keyword')
            ->fieldAttrib('class', 'searchText')
            ->fieldAttrib('autocomplete', 'off')
        ->addField('submit', 'search')
            ->fieldValue('')
            ->fieldAttrib('class', 'searchButton')
            ->fieldAction('false;');
        ?>
</div>

<!-- Show page path -->
<p class="path">
    <?=$this->navigation()->breadcrumbs()
        ->setLinkLast(true)?>
</p>

<!-- Left vertical DIV -->
<div class="lft divinline">

    <div class="menu">

        <div class="mtl"></div>
        <div class="mtr"></div>

        <?=$this->navigation()->menu()
            ->setMaxDepth(2)
            ->setUlClass('body')
            ->setRenderParents(true)?>

        <div class="menubtm"></div>
    </div>

<!-- end of LEFT class and start of RIGHT -->
</div><div class="rght divinline">

    <div class="article<?=!$this->article->showRightColumn ? " noRightCol" : false?>">
        <div class="title"><?=$this->article->title?></div>

        <? if ($this->article->published):?>
            <p style="color: <?=Model_Colors::LIGHT_GRAY?>">
                published on <?=$this->article->published?>
            </p>
        <? endif; ?>

        <?=$this->article->text?>

    </div>

    <? if ($this->article->concepts): ?>
        <ul class="concepts">
        <? foreach ($this->article->concepts as $concept): ?>
            <li>
                <a href="<?=$this->staticUrl($concept->page)?>"><?=$concept->title?></a>
            </li>
        <? endforeach; ?>    
        </ul>
    <? endif; ?>

    <? if ($this->article->showRightColumn): ?> 
        <div class="right">
            <ul class="steps">

                <!-- ?=$this->render('static/liveperson.phtml')? -->

                <? if ($this->article->steps): ?>
                    <? foreach($this->article->steps as $step):?>
                        <li>
                            <a href="<?=$this->staticUrl($step->page)?>"><?=$step->title?></a>
                        </li>
                    <? endforeach; ?>
                <? endif; ?>
            
            </ul>
                            
            <? if ($this->article->term):?>
                <p class="term">
                    Citation from our software development contract:
                    <?=$this->article->term?>
                </p>
            <? endif; ?>

        </div>
    <? endif; ?>

<!-- end of RIGHT -->
</div>    

<!-- wide line at the bottom of the page -->
<p class="wl">
    
    <!--
    <span>
        <script type='text/javascript' src='http://w.sharethis.com/button/sharethis.js#tabs=post%2Cemail%2Cweb&amp;charset=utf-8&amp;style=rotate&amp;publisher=bd1d09bf-bb3e-433e-aa72-29bfdfa237d9&amp;headerbg=%237d8f9b&amp;inactivebg=%235a5a5a&amp;inactivefg=%23ffffff&amp;linkfg=%230093d0'></script>
    </span>    
    -->

    <span class="rev">
        Last update on <span style="color:<?=Model_Colors::BLUE?>"><?=$this->article->updated->get(Zend_Date::DATE_MEDIUM)?></span>
    </span>
</p>

