<? if (APPLICATION_ENV === 'production'): ?>

    <? 

        $IMAGE = "http://www.technoparkcorp.com/images/lp/";
        $ID = '82837326';
        $HC = 'http://server.iad.liveperson.net/hc/';

        $this->headScript()->appendScript("var lpPosY = 100; var lpPosX = 100; 
            if (typeof(tagVars) == 'undefined') { tagVars = '';}");

        $this->headScript()->appendFile("{$HC}{$ID}/x.js?cmd=file&amp;file=chatScript3&amp;site={$ID}&amp;&amp;imageUrl={$IMAGE}");

        $url = "{$HC}{$ID}/?cmd=file&amp;file=visitorWantsToChat&amp;site={$ID}&amp;byhref=1&amp;imageUrl={$IMAGE}";

        $onclick = "window.open(\"{$HC}{$ID}/?cmd=file&amp;file=visitorWantsToChat&amp;site={$ID}&amp;imageUrl={$IMAGE}&amp;referrer=\"+escape(document.location),
            \"chat{$ID}\",
            \"width=475,height=400,resizable=yes\"); return false;";

        $href = "href='$url' onclick='$onclick'";
    ?>

    <div class="step livechat">
        <img src="<?=$this->staticFile('lp.jpg')?>" alt='LivePerson.com Live Chat Icon' />
        <a <?=$href?>>
        <b>Live chat</b> with our mgmt expert</a>
        <a id='_lpChatBtn' <?=$href?> class='label'>online now</a>
    </div>

<? endif; ?>