<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
 * @version $Id: SRS.phtml 780 2010-02-25 14:22:29Z yegor256@yahoo.com $
-->
 
<?=$this->publish($this->project->deliverables)?>

<h1><tt>@todo</tt> Queue</h1>

<?=$this->table()
    ->setSource($this->project->deliverables->todo)
    ->addColumn('name', 'Name')
    ->addColumn('type', 'Type')
    ->addColumn('todoTickets', 'Tickets')
        ->addConverter('implode(", ", ${a1})')
    ?>
    
