<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
-->
 
<h1>All decisions are being made by "<?=$this->wobot?>"</h1>

<? $files = Model_Decision::getDecisionFiles($this->wobot); ?>

<? $prefix = array(); ?>
<? foreach ($files as $label=>$file): ?>
    <? foreach (array_slice(explode('/', $label), 0, -1) as $i=>$sector): ?>
        <? if (!isset($prefix[$i]) || $sector != $prefix[$i]): ?>
            <? $prefix[$i] = $sector ?>
            <span style="margin-left:<?=$i*10?>px;"><?=$sector?></span><br/>
        <? endif; ?>
    <? endforeach; ?>
    <span style="margin-left:<?=($i+1)*10?>px;">
        <?=$this->link('make/' . Model_Pages_Encoder::encode($label), substr(strrchr($label, '/'), 1), false)?>
    </span><br/>
<? endforeach; ?>