<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
 * @version $Id$
-->
 
<?=$this->publish($this->project->deliverables)?>

<h1><?=_t('Functional Requirements')?></h1>

<?
    $reqs = $this->project->deliverables->functional;
    $reqs->uasort(
        create_function(
            '$a, $b',
            'return $a->priority < $b->priority;'
        )
    );
?>

<?=$this->table()
    ->setSource($reqs)
    ->addFormatter('${a2}->outOfScope', 'color:gray')
    ->addColumn('name', _t('Name'))
    ->addColumn('priority', _t('Pri.'))
    ->addColumn('isAccepted', _t('Acc.'))
        ->addConverter('(${a1} ? ${a2}->attributes["accepted"] : false)')
    ->addColumn('isBaselined', _t('Base.'))
        ->addConverter('(${a1} ? "yes" : false)')
    ->addColumn('type', 'Design')
        ->addConverter(
            FaZend_Callback::factory(
                '${a2}->getDesignMap(${i1})'
            )
            ->inject($this->project)
        )
        ->addFormatter('true', 'font-family:Courier; white-space:pre')
    ->addColumn('description', _t('Description'))
    ->addColumn('attributes', _t('Attributes'))
    ?>
    
