<h1>Create new payment in the project</h1>

<?=$this->forma()

    ->addField('text', 'original')
        ->fieldLabel('Original amount')
        ->fieldRequired()
        ->fieldAttrib('maxlength', 10)
        ->fieldAttrib('size', 10)
        
    ->addField('textarea', 'details')
        ->fieldLabel('Details of payment')
        ->fieldRequired()
        ->fieldAttrib('cols', 40)
        ->fieldAttrib('rows', 5)

    ->addField('hidden', 'context')
        ->fieldValue($this->project->name)
        
    ->addField('submit')
        ->fieldAction($this->project->payments, 'createGeneric')
    ?>