<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
-->
 
<h1>Pay one of stakeholders</h1>

<?=$this->forma()

    ->addField('text', 'user')
        ->fieldLabel('User to pay')
        ->fieldRequired()
        
    ->addField('text', 'original')
        ->fieldLabel('Original amount')
        ->fieldRequired()
        ->fieldAttrib('maxlength', 10)
        ->fieldAttrib('size', 10)
        
    ->addField('textarea', 'details')
        ->fieldLabel('Details of payment')
        ->fieldRequired()
        ->fieldAttrib('cols', 40)
        ->fieldAttrib('rows', 5)

    ->addField('hidden', 'context')
        ->fieldValue($this->project->name)
        
    ->addField('submit')
        ->fieldAction($this->project->payments, 'createSpecific')
    ?>