<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
 * @version $Id$
-->
 
<?=$this->publish($this->project->baselines)?>

<h1><?=_t('Project Baselines')?></h1>

<?=$this->table()
    ->setSource($this->project->baselines)
    ->addColumn('__key', _t('Name'))
    ->addColumn('description', _t('Description'))
    ->addColumn('length', _t('Length'))
    ->addOption('switch to', '?switch={__key}')
    ->addOption('diff', '?diff={__key}'/*, '${a2} == "trunk"'*/)
    ->addOption('__key', '?view={__key}')
    ?>
    
<? if ($name = $this->httpGet('diff')): ?>
    
    <h2>Diff between "<?=$name?>" and "trunk":</h2>
    <?=$this->diff(
        $this->project->baselines[$name]->text,
        $this->project->baselines['trunk']->text
    )?>
    
<? elseif ($name = $this->httpGet('view')): ?>
    
    <h2>Baseline "<?=$name?>":</h2>
    <pre>
<?=$this->project->baselines[$name]->text?></pre>

<? else: ?>

    <h2>Current project snapshot:</h2>
    <pre>
<?=$this->project->baselines['trunk']->text?></pre>

<? endif; ?>
