<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
-->
 
<? $this->includeCSS('pages/projects/_any/Integration/Metrics/tree.css') ?>

<?=$this->publish($this->project->metrics)?>

<h1>Project Metrics (full list)</h1>

<?=$this->forma()
    ->addAttrib('class', 'inline')
    ->addBehavior('flash', "Metric '%s' reloaded", '{name}')
    ->addBehavior('redirect')
    ->addField('text', 'name')
        ->fieldLabel('Metric')
        ->fieldAttrib('size', 50)
        ->fieldRequired(true)
    ->addField('submit', 'submit')
        ->fieldValue('Ping')
        ->fieldAttrib('class', 'btn')
        ->fieldAction($this->project->metrics, 'offsetGet')
    ?>

<?=$this->tree()
    ->setCollection($this->project->metrics, 'name', '/')
    ->setOptions(
        array(
            'useAjax' => true,
        )
    )
    ->addAttrib('class', 'tree')
    ->setMask('%s: <b>%s</b>/%s/%s/%s')
    ->addToken('->suffix')
    ->addToken('->value')
    ->addToken('->default')
    ->addToken('->objective')
    ->addToken('->delta')
    ?>

<? $this->headScript()->appendScript('
    $(document).ready(
        function()
        {
            $("div.tree span").bind(
                "click", 
                function()
                {
                    $("input#name").val($(this).html());
                }
            );
        } 
    );
') ?>

