<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
-->
 
<?=$this->publish($this->project->metrics)?>

<h1>Project Metrics (full list)</h1>

<?=$this->table()
    ->setSource($this->project->metrics)
    ->addColumn('__key', 'Name')
    ->addColumn('default', 'Default')
    ->addColumn('value', 'Value')
    ->addColumn('target', 'Target')
    ->addColumn('delta', 'Delta')
    
    ->addOption('target', 'set/{id}')
    ?>

