<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
 * @version $Id$
-->
 
<?=$this->publish($this->project->objectives)?>

<h1>Project Objectives</h1>

<?=$this->forma()
    ->addAttrib('class', 'inline')
    ->addBehavior('flash', '"Objective \'{${a1}->name}\' set to \'{${a2}}\'"')
    ->addBehavior('redirect')
    ->addField('text', 'a1')
        ->fieldLabel('Objective')
        ->fieldAttrib('size', 40)
        ->fieldRequired(true)
        ->fieldConverter(
            FaZend_Callback::factory('${i1}[${a1}]')
            ->inject($this->project->metrics)
        )
    ->addField('text', 'a2')
        ->fieldLabel('Value')
        ->fieldAttrib('size', 5)
        ->fieldAttrib('maxlength', 5)
        ->fieldRequired(true)
    ->addField('submit', 'submit')
        ->fieldValue('Set')
        ->fieldAttrib('class', 'btn')
        ->fieldAction('false; ${a1}->objective = ${a2}')
    ?>

<?=$this->table()
    ->setSource($this->project->metrics)
    ->addConverter('(${a2}->visible ? true : false)')
    ->addColumn('__key', 'Name')
        ->addConverter('"<span onclick=\'set()\'>{${a1}}</span>"')
        ->allowRawHtml()
    ->addColumn('objective', 'Objective')
        ->addFormatter('(${a2}->objective == ${a2}->default ? false : true)', 'font-weight:bold')
    ->addColumn('default', 'Default')
    ->addColumn('value', 'Value')
    ?>
    
    