<?

    $this->includeCSS('panel.css');
    $this->includeJQuery();
    $this->headTitle('thePanel');

?><?=$this->doctype()?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>  
    <?=$this->headTitle()?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
    <?=$this->headStyle()?>
</head> 
<body>

    <div class="header">

        <div class="path">
            <?=$this->navigation(Model_Pages::getInstance($this->doc))
                ->setAcl(Model_Pages::getInstance()->getAcl())
                ->setRole(Model_User::me()->email)
                ->breadcrumbs()
                ->setSeparator(' / ')
                ->setMinDepth(0)
                ->setPartial('panel/header.phtml')
                ->setLinkLast(true)?>
        </div>

        <div class="logo">
            <span class="logo">thePanel<sup style="font-size: 0.3em;">TM</sup> v2.0</span>
            <?=$this->escape(Model_User::me()->email)?>
        </div>

        <div class="r1"></div>
        <div class="r2"></div>
        <div class="r3"></div>

    </div>

    <div class="wrapper">

        <?=$this->flashMessage()?>

        <?=$this->layout()->content?>

    </div>

    <div class="btm">
        <span>(c) <?=date('Y')?> TechnoPark Corp., rev.<?=FaZend_Revision::get()?>, <?=$this->pageLoadTime()?></span>
    </div>

    <?=$this->headScript() ?>
</body>
</html>