<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
-->
 
<?

    $this->headMeta()
        ->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8');

    $this->includeCSS('panel.css');
    $this->includeJQuery();
    $this->headTitle('thePanel');

?><?=$this->doctype()?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>  
    <?=$this->headTitle()?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
    <?=$this->headStyle()?>
</head> 
<body>

    <div class="header">

        <? if (Model_Pages::getInstance()->getAcl()->hasRole(Model_User::me()->email)): ?>
            <div class="path">
                <?=$this->navigation(Model_Pages::getInstance())
                    ->setAcl(Model_Pages::getInstance()->getAcl())
                    ->setRole(Model_User::me()->email)
                    ->breadcrumbs()
                    ->setSeparator(' / ')
                    ->setMinDepth(0)
                    ->setPartial('panel/header.phtml')
                    ->setLinkLast(true)?>
            </div>
        <? endif; ?>

        <div class="logo">
            <a class="logo" href="<?=$this->panelUrl('root')?>" title="Home">thePanel<sup style="font-size: 0.3em;">TM</sup> v2.0</a>
            <?=$this->escape(Model_User::me()->email)?>
        </div>

        <div class="r1"></div>
        <div class="r2"></div>
        <div class="r3"></div>

    </div>

    <div class="wrapper">

        <?=$this->flashMessage()?>

        <?=$this->layout()->content?>

    </div>

    <div class="btm">
        <span>(c) <?=date('Y')?> TechnoPark Corp., 
        rev.<?=FaZend_Revision::get()?>, <?=$this->pageLoadTime()?><br/>
        your IP: <?=$_SERVER['REMOTE_ADDR']?>, load avg: 
        <?=implode(', ', array_map(
            create_function('$a', '$a = round($a, 2); return $a < 3 ? $a : "<span style=\'color:red;\'>$a</span>";'), 
            sys_getloadavg()
        ))?><br/>
        <?=Zend_Date::now()?>
        </span>
    </div>

    <?=$this->headScript() ?>
</body>
</html>