<h1>Delete "<?=$this->skill->name?>" skill of <?=$this->supplier->name?></h1>

<?=$this->forma()

    ->addField('hidden', 'skill')
        ->fieldValue($this->skill)
        
    ->addField('textarea', 'reason')
        ->fieldLabel('Why are you doing this?')
        ->fieldRequired()
        ->fieldAttrib('cols', 50)
        ->fieldAttrib('rows', 5)

    ->addField('submit')
        ->fieldAction($this->supplier, 'deleteSkill')
    ?>