<? $statement = $this->root->statements[$this->segment()] ?>

<h1>Statement for <?=$statement->supplier?></h1>

<p>Balance: <b><?=$statement->balance?></b>,
    Volume: <b><?=$statement->volume?></b> 
    (<?=count($statement)?> payments).</p>

<?=$this->table()
    ->setSource($statement)
    ->addColumn('created', 'Date')
    ->addColumn('usd', 'Amount')
    ->addColumn('rate', 'Rate')
    ->addColumn('context', 'Context')
    ->addColumn('reason', 'Reason')
    ->addColumn('details', 'Details')
    ?>
