<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
 * @version $Id$
-->
 
<h1>Create new payment</h1>

<?=$this->forma()
    ->addBehavior('flash', 'sprintf("Payment added")')
    ->addBehavior('redirect')
    ->addField('text', 'original')
        ->fieldLabel('Original amount', true)
        ->fieldAttrib('maxlength', 10)
        ->fieldAttrib('size', 10)
        ->fieldConverter('new FaZend_Bo_Money(${a1})')
        
    ->addField('textarea', 'details')
        ->fieldLabel('Details of payment', true)
        ->fieldAttrib('cols', 40)
        ->fieldAttrib('rows', 5)

    ->addField('text', 'context')
        ->fieldLabel('Context')
        
    ->addField('text', 'reason')
        ->fieldLabel('Reason of payment')

    ->addField('text', 'supplier')
        ->fieldLabel('Beneficiary\'s email', true)
        ->fieldAttrib('size', 25)

    ->addField('text', 'rate')
        ->fieldLabel('Rate per hour')
        ->fieldAttrib('size', 15)
        ->fieldConverter('new FaZend_Bo_Money(${a1})')

    ->addField('submit')
        ->fieldAttrib('class', 'btn')
        ->fieldAction(array('thePayment', 'create'))
    ?>
    