<div style="float:left; margin-right: 20px;">
    <?=$this->icon('supplier')?>
</div>

<p>
    <b><?=$this->supplier->name?></b>, <?=$this->supplier->countryName?><br/>
    <a href="mailto:<?=$this->supplier->email?>"><?=$this->supplier->email?></a>
    </p>
<p style="clear:both;"></p>

<?=$this->bar()
    ->addLink('ability/create', 'Add new Role')
    ->addLink('skill/create', 'Add new Skill')
    ->addLink('record/create', 'Add new Record')
    ?>

<?=$this->table()
    ->setSource($this->supplier->attachments)
    ->addColumn('name', 'Name')
    ->addColumn('description', 'Description')
    ->addColumn('hasFile', 'Attachment')
    ?>
