
<?=$this->icon('wobot')?><br/>
<?=$this->wobot?> (<?=$this->wobot->getHumanName()?>, <tt><?=$this->wobot->getEmail()?></tt>)

<?=$this->bar()
    ->addLink('decisions', 'Decisions')
    ->addLink('clean', _t('Clean entire history (%d)', 
        count(Model_Decision_History::retrieveByWobot($this->wobot))))
    ?>

<?=$this->table()
    ->setSource(Model_Decision_History::retrieveByWobotNonEmpty($this->wobot))
    ->addFormatter('->isRunning()', 'color:gray')
    ->addFormatter('->isError()', 'color:red')

    ->addColumn('created', 'Date')
    ->addColumn('getTitle', 'Title')
    ->addColumn('result', 'Decision made')

    ->addOption('created', 'decisions/{__id}')
    ?>