
<?=$this->icon('wobot')?><br/>
<?=$this->wobot?> (<?=$this->wobot->getHumanName()?>, <tt><?=$this->wobot->getEmail()?></tt>)

<?=$this->bar()
    ->addLink('decisions', 'Decisions')
    ->addLink('clean', 'Clean entire history')
    ?>

<?=$this->table()
    ->setSource(Model_Decision_History::retrieveByWobotNonEmpty($this->wobot))

    ->addColumn('created', 'Date')
    ->addColumn('getTitle', 'Title')
    ->addColumn('result', 'Decision made')

    ->addOption('created', 'decisions/{__id}')
    ?>