<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
-->
 
<?
$xml = new DOMDocument('1.0', 'utf-8');
$xml->formatOutput = true;
$root = $xml->createElement('urlset');
$root->setAttribute('xmlns', 'http://www.sitemaps.org/schemas/sitemap/0.9');
$xml->appendChild($root);

foreach ($this->navigation()->findAllBy('map', true) as $page) {
    $article = Model_Article::createByLabel($page->path);
    $url = $xml->createElement('url');
    $url->appendChild(
        $xml->createElement(
            'loc', 
            $this->serverUrl() . $this->staticUrl($article->page)
        )
    );
    $date = ($article->isPublished() ? $article->published : Zend_Date::now());
    $url->appendChild(
        $xml->createElement(
            'lastmod', 
            $date->get('Y-MM-dd')
        )
    );
    $root->appendChild($url);
}    

Zend_Controller_Front::getInstance()->getResponse()
    ->setHeader('Content-Type', 'application/xml')
    ->setBody($xml->saveXML());
?>