<?=$this->article->text?>

<? foreach (Model_Article::lucene()->find(Zend_Controller_Front::getInstance()->getRequest()->getPost('keyword')) as $hit): ?>

    <? $article = Model_Article::createByLabel($hit->path) ?>
            
    <p>
        <a title="<?=$this->escape($page->title)?>" href="<?=$this->staticUrl($page->path)?>"><?=$this->escape($page->title)?></a><br/> 
        ......
    </p>

<? endforeach; ?>

