<?=$this->article->text?>

<? foreach (Model_Article::lucene()->find(Zend_Controller_Front::getInstance()->getRequest()->getPost('keyword')) as $hit): ?>

    <? $doc = $hit->getDocument(); ?>

    <? $article = Model_Article::createByLabel($doc->page); ?>
            
    <p>
        <b><a title="<?=$article->title?>" 
            href="<?=$this->staticUrl($article->page)?>"><?=$article->title?></a></b><br/> 
        <?=$this->escape($article->description)?>
    </p>

<? endforeach; ?>

