<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
-->
 
<? 
    list($month, $year) = explode('-', $this->segment());
    $start = new Zend_Date("$month-1-$year");
    $end = clone $start;
    $end->add(1, Zend_Date::MONTH);
?>
 
<h1>Performance Report for 
    <?=$start->get(Zend_Date::MONTH_NAME . ' ' . Zend_Date::YEAR)?></h1>

<p>Suppliers' results:</p>
<?=$this->table()
    ->setInjection('earned', $earned = new FaZend_Bo_Money())
    ->setSource(thePayment::retrieveSummaryByInterval($start, $end))
    ->addColumn('supplier', 'Email')
    ->addColumn('earned', 'Earned')
        ->addFormatter(
            'callback',
            create_function(
                '$value, $row, $table', 
                '$table->getInjection("earned")->add($value); return false;'
            )
        )
    ->addColumn('paid', 'Paid')
    ?>
    
<p>They totally earned <?=$earned?>, PMO bonus: <?=$earned->div(10)?></p>

<p>Suppliers approved during the reporting period:</p>

<?=$this->table()
    ->setSource($this->root->supplierRegistry->retrieveApprovedByInterval($start, $end))
    ->setInjection('pmoBonus', $pmoBonus = new FaZend_Bo_Money())
    ->addColumn('email', 'Email')
    ->addColumn('name', 'Full name')
    ->addColumn('skills', 'Skills')
        ->addConverter(
            'callback', 
            create_function('$a', 'return implode(", ", $a);')
        )
    ->addColumn('roles', 'Roles')
        ->addConverter(
            'callback', 
            create_function('$a', 'return implode(", ", $a);')
        )
    ->addColumn('rate', 'Rate')
    ->addColumn('pmoBonus', 'Bonus')
        ->addFormatter(
            'callback',
            create_function(
                '$value, $row, $table', 
                '$table->getInjection("pmoBonus")->add($value); return false;'
            )
        )
    ?>

<p>PMO bonus: <?=$pmoBonus?></p>

<p>Total PMO bonus for the period: 
    <b><?=$pmoBonus->add($earned)?></b></p>
