
[projects]
    <?=Model_Pages::ADMIN?> = r
    <?=Model_Project_Test::PM?> = r

[wobots]
    <?=Model_Pages::ADMIN?> = rw
    <?=Model_Project_Test::PM?> = r

<? foreach (Model_Process::retrieveAll() as $process): ?>
    [<?=$process?>]
    <?=Model_Pages::ADMIN?> = rw
    <?=Model_Project_Test::PM?> = r
    <? if (!$process->projectExists()): ?>
        <? continue; ?>
    <? endif; ?>
    <? foreach ($process->getProject()->getStakeholders() as $stakeholder=>$password): ?>
        <?=$stakeholder?> = rw
    <? endforeach; ?>
<? endforeach; ?>
