[root]
    * = r

[projects]
    <?=Model_Pages::ADMIN?> = r

[wobots]
    <?=Model_Pages::ADMIN?> = rw

<? foreach (Model_Process::retrieveAll() as $process): ?>
    [<?=$process?>]
    <?=Model_Pages::ADMIN?> = rw
    <? if (!$process->projectExists()): ?>
        <? continue; ?>
    <? endif; ?>
    <? foreach ($process->getProject()->getStakeholders() as $stakeholder=>$password): ?>
        <?=$stakeholder?> = rw
    <? endforeach; ?>
<? endforeach; ?>
