<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
-->
 
<p>Full list of wobots in the system (working now):</p>

<?=$this->gallery()
    ->setSource(Model_Wobot::retrieveAll())
    ->setIcon('wobot')
    ->setLink('{getFullName}')
    ?>

<?=$this->forma()
    ->addAttrib('class', 'invisible')
    ->addBehavior('flash', 'POS was clean out successfully')
    ->addBehavior('redirect')
    ->addField('submit', 'submit')
        ->fieldValue('Clean POS Database')
        ->fieldAttrib('class', 'btn')
        ->fieldAction('FaZend_Pos_Properties', 'cleanOut')
    ?>

