<h1>Add new Supplier to the Database</h1>

<?=$this->forma()

    ->addField('text', 'email')
        ->fieldLabel('Email')
        ->fieldRequired()
        ->fieldAttrib('maxlength', 120)
        ->fieldAttrib('size', 40)
        
    ->addField('text', 'name')
        ->fieldLabel('Full name')
        ->fieldRequired()
        ->fieldAttrib('maxlength', 80)
        ->fieldAttrib('size', 30)

    ->addField('select', 'country')
        ->fieldLabel('Country of permanent location')
        ->fieldRequired()
        ->fieldOptions(Zend_Locale::getTranslationList('territory', null, 2), true)

    ->addField('submit')
        ->fieldAction($this->registry, 'createSupplier')
    ?>