<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
 * @version $Id$
-->
 
<?
    // start logging to memory
    FaZend_Log::getInstance()->addWriter('Memory', 'publish');

    Zend_Db_Table::getDefaultAdapter()->beginTransaction();
    
    // explicitly reload the document
    $this->document->reload();

    // save all changes made to POS, if they were made
    FaZend_Pos_Properties::saveAll();

    Zend_Db_Table::getDefaultAdapter()->commit();

    // stop logging to memory
    $log = FaZend_Log::getInstance()->getWriterAndRemove('publish')->getLog();
?>

<p>Document '<?=$this->document->ps()->path?>' reloaded:</p>

<pre><?=$log?></pre>
