<? $request = $this->root->projectRegistry->getStaffRequestById($this->segment()) ?>
<? $response = $this->root->supplierRegistry->resolve($request) ?>

<h1>Staff Response for '<?=$request->role?>' in '<?=$request->project?>'</h1>

<p>
    Skills required: <?=$request->skillsHtml?><br/>
    Estimated engagement duration: <?=$request->duration?> days<br/>
    Cost expected: <?=$request->cost?><br/>
    Quality Threshold: <?=$request->threshold?>%
</p>

<p>Already in the project:</p>
<ul>
<? foreach ($request->project->staffAssignments->retrieveStakeholdersByRole($request->role) as $stakeholder): ?>
    <li><?=$stakeholder?>:
    <?=$stakeholder->getPaidInProject($request->project)?> paid already</li>
<? endforeach; ?>
</ul>

<p>Candidates:</p>
<? $index = 0; ?>
<? foreach ($response as $item): ?>

    <? if ($index++ < 3): ?>

        <p><span style="color:<?=($item->quality > $request->threshold ? Model_Colors::GREEN : Model_Colors::RED)?>;
            font-size:2em;font-weight:bold;"><?=$item->quality?>%</span>: 
            <b><?=$item->supplier->name?></b>
            (<a href="mailto:<?=$item->supplier->email?>"><?=$item->supplier->email?></a>), 
            <?=$item->supplier->rate?></p>
        <pre><?=$item->reason?></pre>

    <? else: ?>
    
        <p><?=$item->quality?>%: <b><?=$item->supplier->name?></b>
        (<?=$item->supplier->email?>), <?=$item->supplier->rate?></p>
    
    <? endif; ?>

<? endforeach; ?>