<!-- this script is called by breadcrumbs() helper -->

<? $first = true; ?>

<? foreach ($this->pages as $page): ?>

    <? if (!$first): ?>
        &#32;/&#32;
    <? else: ?>
        <? $first = false; ?>
    <? endif; ?>

    <? $id = 'header_' . md5($page->title); ?>

    <? $label = $this->escape(cutLongLine($page->label, 20)) ?>
    <? if (Model_Pages::getInstance()->hasScript($page->title)): ?>
        <span id="<?=$id?>" class="page">
            <a href="<?=$this->panelUrl($page->title)?>"
                title="<?=_t('go to %s', $this->escape($page->title))?>"><?=$label?></a
                ><? if ($page->parent->count() > 1): ?><span
                onclick="selector($('#<?=$id?>'), '<?=$page->title?>')"
                title="<?=_t('click to change')?>">&darr;</span>
            <? endif; ?>
        </span>
    <? else: ?>
        <?=$label?>
    <? endif; ?>

<? endforeach; ?>

<? $this->includeJS('header.js'); ?>