<!-- this script is called by breadcrumbs() helper -->

<? $first = true; ?>

<? foreach ($this->pages as $page): ?>

    <? if (!$first): ?>
        &#32;/&#32;
    <? else: ?>
        <? $first = false; ?>
    <? endif; ?>

    <? $id = 'header_' . md5($page->title); ?>

    <span id="<?=$id?>" class="page">
        <a href="<?=$this->panelUrl($page->title)?>"><?=$page->label?></a><span
            onclick="selector($('#<?=$id?>'), '<?=$page->title?>')"
            title="click to change">&darr;</span>
    </span>

<? endforeach; ?>

<? $this->includeJS('header.js'); ?>