<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
-->

<html>
<head>
<? $this->includeCSS('panel.css');?>
<?=$this->headTitle()?>
<?=$this->headMeta()?>
<?=$this->headLink()?>
<?=$this->headStyle()?>
</head>
<body style="padding:30px; font-size: 1.2em;">
    
<?=$this->forma()
    ->addBehavior('redirect')
    ->addField('text', 'email')
        ->fieldLabel('Email')
        ->fieldAttrib('size', 30)
    ->addField('text', 'password')
        ->fieldLabel('Password')
        ->fieldAttrib('size', 20)
        ->fieldAttrib('type', 'password')
    ->addField('submit')
        ->fieldValue('Login')
        ->fieldAttrib('class', 'btn')
        ->fieldAction(
            '
            false;
            $resolver = new Model_Auth_Resolver();
            $found = false;
            $possible = array();
            do {
                $pwd = $resolver->resolve(${email}, "");
                if ($pwd == ${password}) {
                    $found = true;
                    break;
                }
                $possible[] = $pwd;
            } while ($pwd && $resolver->hasMore());
            if (!$pwd) {
                FaZend_Log::err("Invalid login attempt: " . ${email});
                FaZend_Exception::raise(
                    "Login_Exception",
                    "User with this email is not found"
                );
            }
            if (!$found) {
                FaZend_Log::err(
                    "Invalid password provided for " . ${email} 
                    . " (\'" . implode("\', \'", $possible) . "\' expected)"
                );
                FaZend_Exception::raise(
                    "Login_Exception",
                    "Invalid password"
                );
            }
            Model_User::logIn(${email});
            '
        )
    ?>
</body>
</html>