<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
-->
 
<h1><?=_t('Access restricted')?></h1>

<? if (Model_Pages::getInstance()->getAcl()->hasRole(Model_User::me()->email)): ?>

    <p class="flash">
        <? if ($this->message): ?>
            <?=$this->message?>
        <? else: ?>
            <?=_t('Unknown reason of access restriction, refer to admin')?>
        <? endif; ?>
    </p>

    <p><?=_t('This particular document is not available for you. 
    Here is a list of documents that you can access:')?></p>

    <p><?=$this->navigation(Model_Pages::getInstance())
        ->menu()
        ->setAcl(Model_Pages::getInstance()->getAcl())
        ->setRole(Model_User::me()->email)
        ->setMaxDepth(1)
        ?></p>
        
<? else: ?>

    <p><?=_t('You don\'t have enough access permissions to access this management panel, 
        although your email (<tt>%s</tt>) is registered in one of the projects we manage. 
        Refer to the sponsor or the project manager of your project for obtaining 
        required access rights. Sorry for any inconveniences.',
        Model_User::me()->email)?></p>

<? endif; ?>
