<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
-->
 
<? $request = $this->root->projectRegistry->getStaffRequestById($this->segment()) ?>
<? $response = $this->root->supplierRegistry->resolve($request) ?>

<h1>Staff Response for '<?=$request->role?>' in '<?=$request->project?>'</h1>

<p>
    Skills required: <?=$request->skillsHtml?><br/>
    Estimated engagement duration: <?=$request->duration?> days<br/>
    Cost expected: <?=$request->cost?><br/>
    Quality Threshold: <?=$request->threshold?>%
</p>

<p>Suggested candidates:</p>
<? $index = 0; ?>
<? foreach ($response as $item): ?>

    <? if (isset($request->project->staffAssignments[$item->supplier->email])): ?>
        <? $paid = '[' . $request->project->staffAssignments[$item->supplier->email]
            ->getPaidInProject($request->project) . ' paid already]' ?>
    <? else: ?>
        <? $paid = false; ?>
    <? endif; ?>

    <? if ($index++ < 3): ?>
        <p><span style="color:<?=($item->quality > $request->threshold ? Model_Colors::GREEN : Model_Colors::RED)?>;
            font-size:2em;font-weight:bold;"><?=$item->quality?>%</span>: 
            <b><?=$item->supplier->name?></b>
            (<a href="mailto:<?=$item->supplier->email?>"><?=$item->supplier->email?></a>), 
            <?=$item->supplier->rate?>
            &nbsp;<span style="color:green"><?=$paid?></span></p>
        <pre><?=$item->reason?></pre>
    <? else: ?>
        <p><?=$item->quality?>%: <b><?=$item->supplier->name?></b>
        (<?=$item->supplier->email?>), <?=$item->supplier->rate?>
        &nbsp;<span style="color:green"><?=$paid?></span></p>
    <? endif; ?>

<? endforeach; ?>