<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
-->
 
<?=$this->publish($this->project->traceability)?>

<? $class = $this->segment() ?>

<h1>Traceability of class <tt><?=$class?></tt></h1>

<? foreach ($this->project->traceability->getSourcesByType($class) as $source): ?>
    <p><b><?=$source->name?></b> traces to:</p>
    <ul>
    <? foreach ($this->project->traceability->getLinksBySource($source) as $link): ?>
        <li><?=$link->toName?> [<?=$link->deep?>/<?=$link->coverage?>] 
            <span style="color:gray;"><?=$link->explanation?></span></li>
    <? endforeach; ?>
    </ul>
<? endforeach; ?>