<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
-->
 
<?=$this->publish($this->project->schedule)?>

<? $this->includeCSS('pages/projects/_any/Time/GanttChart/table.css') ?>

<h1>Gantt Chart</h1>

<? $finish = $this->project->schedule->finish->setWeekday(7) ?>
<? $start = new FaZend_Date(Zend_Date::now()
    ->setHour(0)
    ->setMinute(0)) ?>
<? $increment = Zend_Date::DAY ?>
<? if ($increment == Zend_Date::WEEK) $start->setWeekday(1) ?>
<? $date = clone $start; ?>

<p>Start on <?=$start->get(Zend_Date::DATE_SHORT)?>, 
    finish estimated on <b><?=$finish->get(Zend_Date::DATE_SHORT)?></b>,
    <?=count($this->project->schedule->activities)?> activities.</p>

<table class="chart">
<tr>
    <td><!-- activity --></td>
    <td><!-- cost --></td>
    <td><!-- days --></td>
    <td><!-- preds --></td>
    <td><!-- criteria --></td>
    <? 
    $date->set($start);
    $currentMonth = $date->get(Zend_Date::MONTH_NAME_SHORT); 
    $i = 0;
    do {
        $date->add(1, $increment);
        $i++;
        
        if (($date->get(Zend_Date::MONTH_NAME_SHORT) != $currentMonth)
        || !$date->isEarlier($finish)) {
            echo "<th colspan='{$i}' halign='center'>{$currentMonth}</th>";
            $i = 0;
        }
        $currentMonth = $date->get(Zend_Date::MONTH_NAME_SHORT);
    } while ($date->isEarlier($finish));
    ?>
</tr>
<tr>
    <th style="width: 280px !important;">Activity</th>
    <th width="70px">Cost</th>
    <th>Days</th>
    <th>Preds</th>
    <th>Crit.</th>

    <? for ($date->set($start); $date->isEarlier($finish); $date->add(1, $increment)): ?>
        <th><?=$date->get($increment)?></th>
    <? endfor; ?>
</tr>

<? $weekEnd = new FaZend_Date() ?>
<? foreach ($this->project->schedule->activities as $activity): ?>
<tr>
    <td><?=cutLongLine($activity->sow, 50)?></td>
    <td><?=$activity->cost?></td>
    <td><?=$activity->duration?></td>
    <td><?=count($activity->predecessors)?></td>
    <td><?=count($activity->criteria)?></td>
    
    <? for ($date->set($start); $date->isEarlier($finish); $date->add(1, $increment)): ?>
        <? $weekEnd->set($date); $weekEnd->add(1, $increment)?>
        <td
        <? if (
            // start of this week is inside the activity
            $date->isBetween($activity->start, $activity->finish)
            // end of this week is inside the activity
            || $weekEnd->isBetween($activity->start, $activity->finish)
            // start and end are inside this week
            || $activity->start->isBetween($date, $weekEnd)
            ): ?>
            class="<?=$activity->cost ? 'busy' : 'milestone'?>"
        <? endif; ?>
        ></td>
    <? endfor; ?>

</tr>
<? endforeach; ?>
</table>
