Could you please provide your cost and duration estimates for this task. 
You should NOT start implementing it now, just give me your estimates.

Here you can find more detailed information about the work you need to do: 
<?=$this->sharedDoc($this->activityDoc)?>

--

Please, give me your cost and duration estimates using the fields in this ticket.

More info about the work to be done you can find here: 
<?=$this->sharedDoc($this->activityDoc)?>
