<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
-->
 
<? $history = new Model_Decision_History($this->segment(3)); ?>
<? $protocol = explode("\n", $history->getProtocol()) ?>

<p>
    Date: <?=$history->created?><br/>
    Title: "<?=$history->getTitle()?>"<br/>
    Hash: "<?=$history->hash?>"<br/>
    Decision made: <b><?=$history->result?>
        <?=$history->isRunning() ? " (pid: {$history->getPid()})" : false?></b>
</p>

<p>Protocol (<?=count($protocol)?> lines):</p>

<!-- very long PRE cause problems for browser -->
<? foreach (array_chunk($protocol, 50) as $chunk): ?>
    <pre><?=implode("\n", $chunk)?></pre>
<? endforeach; ?>