<? $decision = new Model_Decision_History($this->segment(3)); ?>

<p>
    Date: <?=$decision->created?><br/>
    Title: "<?=$decision->getTitle()?>"<br/>
    Decision made: <b><?=$decision->result?></b>
</p>

<p>Protocol:</p>

<!-- very long PRE cause problems for browser -->
<? foreach (array_chunk(explode("\n", $decision->protocol), 50) as $chunk): ?>
    <pre>
        <?=implode("\n", $chunk)?>
    </pre>
<? endforeach; ?>