<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
-->
 
<? $statements = $this->root->statements ?>

<h1>Statements</h1>

<?=$this->bar()
    ->addLink('create', 'Create new payment')
    ?>

<p>Balance to pay: <b><?=$statements->balance?></b>,
    volume: <?=$statements->volume?>.</p>

<?=$this->table()
    ->setSource($statements)
    ->addColumn('supplier', 'Email')
    ->addColumn('balance', 'Balance')
    ->addColumn('volume', 'Volume')
    
    ->addOption('supplier', '{supplier}')
    ->addOption('email', '{supplier}/email')
    ?>
    
