<? $statements = $this->root->statements ?>

<h1>Statements</h1>

<?=$this->bar()
    ->addLink('create', 'Create new payment')
    ?>

<p>Balance: <b><?=$statements->balance?></b>,
    Volume: <b><?=$statements->volume?></b>.</p>

<?=$this->table()
    ->setSource($statements)
    ->addColumn('supplier', 'Email')
    ->addColumn('balance', 'Balance')
    ->addColumn('volume', 'Volume')
    ->addOption('supplier', '{supplier}')
    ?>
    
