<? $statements = $this->root->statements ?>

<h1>Statements</h1>

<?=$this->bar()
    ->addLink('create', 'Create new payment')
    ?>

<p>Balance to pay: <b><?=$statements->balance?></b>,
    volume: <?=$statements->volume?>.</p>

<?=$this->table()
    ->setSource($statements)
    ->addColumn('supplier', 'Email')
    ->addColumn('balance', 'Balance')
    ->addColumn('volume', 'Volume')
    
    ->addOption('supplier', '{supplier}')
    ->addOption('email', '{supplier}/email')
    ?>
    
