<h1>Create new Skill for <?=$this->supplier->name?></h1>

<?=$this->forma()

    ->addField('text', 'name')
        ->fieldLabel('Title of the skill')
        ->fieldRequired()
        ->fieldAttrib('maxlength', 100)
        ->fieldAttrib('size', 30)
        
    ->addField('select', 'grade')
        ->fieldLabel('Grade')
        ->fieldRequired()
        ->fieldOptions(theSupplierSkill::getDefaultLevels())

    ->addField('submit')
        ->fieldAction($this->supplier, 'createSkill')
    ?>