<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
 * @version $Id$
-->
 
<?=$this->publish($this->root->opportunityRegistry)?>

<? $opp = $this->root->opportunityRegistry[$this->segment()]?>

<h1>Opportunity "<?=$opp->id?>"</h1>

<?=$this->forma()
    ->addAttrib('class', 'inline')
    ->addBehavior('flash', '"Offer document sent to \'{${a1}}\'"')
    ->addBehavior('redirect')
    ->addField('text', 'email')
        ->fieldLabel('Email')
        ->fieldAttrib('size', 40)
        ->fieldRequired(true)
    ->addField('submit', 'submit')
        ->fieldValue('Send')
        ->fieldAttrib('class', 'btn')
        ->fieldAction(array($opp, 'sendByEmail'))
    ?>

<p>LaTeX source:</p>

<style>
textarea.latex {
    font-family: Courier;
    font-size: 11px;
}
</style>
<textarea class="latex" cols="140" rows="20"><?=$opp->getLatex()?></textarea>

<p>Structure of the document:</p>
    
<pre class="log"><?=$opp->sheets->dump()?></pre>

