<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
-->
 
<? $activity = $this->project->activityList->activities->findById($this->segment())?>

<h1>Activity "<?=$activity->name?>"</h1>

<p>
    Name: <?=$activity->name?><br/>
    Cost: <?=$activity->cost?><br/>
    SOW: <?=$activity->sow?><br/>
    Criteria: <?=$activity->criteria?><br/>
    Predecessors: <?=$activity->predecessors?>
</p>
   
<p> 
    isMilestone: <?=$this->yesNo($activity->isMilestone())?><br/>
    isIssueExist: <?=$this->yesNo($activity->isIssueExist())?><br/>
    isAssigned: <?=$this->yesNo($activity->isAssigned())?><br/>
    isAccepted: <?=$this->yesNo($activity->isAccepted())?><br/>
    isCostEstimated: <?=$this->yesNo($activity->isCostEstimated())?><br/>
    isDurationEstimated: <?=$this->yesNo($activity->isDurationEstimated())?><br/>
    isStarted: <?=$this->yesNo($activity->isStarted())?><br/>
    isClosed: <?=$this->yesNo($activity->isClosed())?>
</p>