<? $activity = $this->project->activityList->activities->findById($this->segment())?>

<h1>Activity "<?=$activity->name?>"</h1>

<? $activity->makeAlive() ?>

<p>
    Name: <?=$activity->name?><br/>
    Cost: <?=$activity->cost?><br/>
    SOW: <?=$activity->sow?><br/>
    Criteria: <?=$activity->criteria?><br/>
    Predecessors: <?=$activity->predecessors?>
</p>
   
<p> 
    isMilestone: <?=$this->yesNo($activity->isMilestone())?><br/>
    isIssueExist: <?=$this->yesNo($activity->isIssueExist())?><br/>
    isAssigned: <?=$this->yesNo($activity->isAssigned())?><br/>
    isAccepted: <?=$this->yesNo($activity->isAccepted())?><br/>
    isCostEstimated: <?=$this->yesNo($activity->isCostEstimated())?><br/>
    isDurationEstimated: <?=$this->yesNo($activity->isCostEstimated())?><br/>
    isStarted: <?=$this->yesNo($activity->isStarted())?><br/>
    isClosed: <?=$this->yesNo($activity->isClosed())?>
</p>