<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
-->
 
<? $this->includeCSS('news.css');?>

<div class="rss">
    <div class="img"></div><br/>
    <a href="<?=$this->staticUrl('about/rss')?>">RSS XML News Feed, Stay updated!</a>
</div>    

<?=$this->article->text?>

<?
    // new holder of news elements
    $news = Zend_Navigation_Page::factory(array('type'=>'uri'));

    foreach ($this->navigation()->findOneBy('path', $this->article->page)->getPages() as $page) {
        // load news article
        $article = Model_Article::createByLabel($page->path);
            
        // save article for future use
        $page->article = $article;

        if (preg_match('/year(\d+)$/', $page->path)) {
            continue;
        }
        // backward chronological order
        $page->order = 1-$article->published->getTimestamp();

        // add the article to the holder, to show later
        $news->addPage($page);
    }

    // new holder of years elements
    $years = Zend_Navigation_Page::factory(array('type'=>'uri'));

    foreach ($this->navigation()->findOneBy('path', 'about/news')->getPages() as $page) {

        // load news article
        $article = Model_Article::createByLabel($page->path);
            
        // save article for future use
        $page->article = $article;

        if (!preg_match('/year(\d+)$/', $page->path, $matches)) {
            continue;
        }
                               
        // backward chronological order
        $page->order = -(int)$matches[1];

        // year label
        $page->year = $matches[1];

        // add the article to the holder, to show later
        $years->addPage($page);

    }
?>

<? foreach ($news as $page): ?>

    <p class="news">
        <b><a href="<?=$page->href?>">
        <?=$page->article->title?></a></b>, 
        <?=$page->article->description?><br/>
        <span>published on <?=$page->article->published->get(Zend_Date::DATE_MEDIUM)?></span>
    </p>


<? endforeach; ?>

<p>Read news from <?=(($this->article->page == 'about/news') ? 'previous' : 'other')?> years:

    <? if ($this->article->page != 'about/news'): ?>
        <a href="<?=$this->staticUrl('about/news')?>">
            <?=date('Y')?>
        </a>
    <? endif; ?>    

    <? foreach ($years as $year): ?> 
        <a title="<?=$year->title?>" href="<?=$year->href?>"><?=$year->year?></a>&#32;&#32;
    <? endforeach; ?>    
</p>
