<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
-->
 
<?
$entries = array();
foreach ($this->navigation()->findOneBy('path', 'about/news')->getPages() as $page) {
    // load news article
    if (preg_match('/year(\d+)$/', $page->path, $matches)) {
        continue;
    }
    $article = Model_Article::createByLabel($page->path);
    $entries[] = array(
        'title' => $article->title,
        'link' => $this->staticUrl($article->page),
        'lastUpdate' => $article->published->getTimestamp(),
        'description' => $article->description,
    );
}    

$feed = Zend_Feed::importArray(
    array(
        'title' => 'TechnoParkCorp.com News Feed',
        'link' => $this->serverUrl(),
        'description' => 'Latest news about TechnoPark Corp. achievements and results',
        'pubDate' => Zend_Date::now()->get(Zend_Date::RSS),
        'generator' => 'TechnoPark Corp.',
        'charset' => 'utf-8',
        'entries' => $entries,
    ), 
    'rss'
);

Zend_Controller_Front::getInstance()->getResponse()
    ->setHeader('Content-Type', 'application/xml')
    ->setBody($feed->saveXML());
?>