<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
-->
 
<?
    $wpName = str_replace('-', theMetrics::SEPARATOR, $this->segment());
    if (strpos($wpName, theActivity::SEPARATOR) !== false)
        list($wpName, $activityName) = explode(theActivity::SEPARATOR, $wpName);

    try {
        $this->wp = $this->project->wbs->findOrMakeWp($wpName);
    } catch (WorkPackageCantBeMade $e) {
        FaZend_Exception::raise('WrongWorkPackageName', 
            "Work package not found with name '{$wpName}', {$e->getMessage()}",
            'AccessRestrictedException');
    }
    
    if (isset($activityName)) {
        try {
                $this->activity = $this->project->activityList->activities
                    ->findByName($wpName . theActivity::SEPARATOR . $activityName);
        } catch (ActivityNotFound $e) {
            FaZend_Exception::raise('WrongActivityName', 
                "Activity not found with name '{$activityName}', {$e->getMessage()}",
                'AccessRestrictedException');
        }
    }
    
?>

<!-- work package to show -->
<? if (!isset($this->activity)): ?>

    <h1>Work Package: "<?=$this->wp->code?>"</h1>

    <? if (!$this->wp instanceof theWpAggregator): ?>
        <p>
            Current metric value: <?=$this->wp->metric->value?><br/>
            Target value: 
                <? if ($this->wp->metric->objective): ?>
                    <?=$this->wp->metric->objective?>
                    <? if ($this->wp->metric->visible): ?>
                        (default: <?=$this->wp->metric->default?>)
                    <? endif; ?>
                <? else: ?>
                    <i>no target</i>
                <? endif; ?><br/>
        </p>
    <? endif; ?>

    <p>
        Cost of Work Package: <b><?=$this->wp->cost?></b>
    </p>

    <?=$this->table()
        ->setSource($this->project->wbs->getWorkPackagesByPrefix($this->wp->code))
        ->addColumn('code', 'Work package')
        ->addColumn('cost', 'Cost')
        ->addColumn('title', 'Statement of work')
        
        ->addOption('code', '../{url}')
        ?>
        
    <h2>Synopsis</h2>
    
    <p><?=$this->wp->code?></p>
        
<!-- activity to show -->
<? else: ?>

    <? if (isset($this->criteria)): ?>
        <? $criteria = $this->criteria ?>
    <? else: ?>
        <? $criteria = $this->activity->criteria ?>
    <? endif; ?>

    <h1>Activity (<?=$this->activity->criteria->isTrue($this->project) ? 
        'completed' : 'not completed yet' ?>)</h1>

    <?=$this->activity->criteria->asHtml($this->project)?>

<? endif; ?>
