<?
    $wpName = str_replace('-', theMetrics::SEPARATOR, $this->segment());
    if (strpos($wpName, theActivity::SEPARATOR) !== false)
        list($wpName, $activityName) = explode(theActivity::SEPARATOR, $wpName);

    try {
        $this->wp = $this->project->wbs->findOrMakeWp($wpName);
    } catch (WorkPackageCantBeMade $e) {
        FaZend_Exception::raise('WrongWorkPackageName', 
            "Work package not found with name '{$wpName}', {$e->getMessage()}",
            'AccessRestrictedException');
    }
    
    if (isset($activityName)) {
        try {
                $this->activity = $this->project->activityList->activities
                    ->findByName($wpName . theActivity::SEPARATOR . $activityName);
        } catch (ActivityNotFound $e) {
            FaZend_Exception::raise('WrongActivityName', 
                "Activity not found with name '{$activityName}', {$e->getMessage()}",
                'AccessRestrictedException');
        }
    }
    
?>

<!-- work package to show -->
<? if (isset($this->wp)): ?>

    <h1>Work Package: "<?=$this->wp->code?>"</h1>

    <? if (!$this->wp instanceof theWpAggregator): ?>
        <p>
            Current metric value: <?=$this->wp->metric->value?><br/>
            Target value: 
                <? if ($this->wp->metric->target): ?>
                    <?=$this->wp->metric->target?>
                    <? if ($this->wp->metric->visible): ?>
                        (default: <?=$this->wp->metric->default?>)
                    <? endif; ?>
                <? else: ?>
                    <i>no target</i>
                <? endif; ?><br/>
        </p>
    <? endif; ?>

    <p>
        Cost of Work Package: <b><?=$this->wp->cost?></b>
    </p>

    <?=$this->table()
        ->setSource($this->project->wbs->getWorkPackagesByPrefix($this->wp->code))
        ->addColumn('code', 'Work package')
        ->addColumn('cost', 'Cost')
        ->addColumn('title', 'Statement of work')
        
        ->addOption('code', '../{url}')
        ?>
        
    <h2>Synopsis</h2>
    
    <?=ticket('PM/scope/WBS/' . $this->wp->code)?>
        
<!-- activity to show -->
<? else: ?>

    <h1>Activity: "<?=$this->activity->name?>"</h1>

    <p>
        Cost: <?=$this->activity->cost?><br/>
        SOW: <?=$this->activity->sow?><br/>
        Criteria: <?=$this->activity->criteria?><br/>
        Predecessors: <?=$this->activity->predecessors?>
    </p>

<? endif; ?>