<h1>Create new Ability for <?=$this->supplier->name?></h1>

<?=$this->forma()

    ->addField('text', 'role')
        ->fieldLabel('Role')
        ->fieldRequired()
        ->fieldAttrib('maxlength', 80)
        ->fieldAttrib('size', 30)
        
    ->addField('text', 'price')
        ->fieldLabel('Price per hour')
        ->fieldRequired()
        ->fieldAttrib('maxlength', 10)
        ->fieldAttrib('size', 10)

    ->addField('textarea', 'reason')
        ->fieldLabel('Why are you doing this?')
        ->fieldRequired()
        ->fieldAttrib('cols', 50)
        ->fieldAttrib('rows', 5)
        
    ->addField('submit')
        ->fieldAction($this->supplier, 'createAbility')
    ?>