<h1>Create New Role for <?=$this->supplier->name?></h1>

<?=$this->forma()

    ->addField('text', 'role')
        ->fieldLabel('Role')
        ->fieldRequired()
        ->fieldAttrib('maxlength', 80)
        ->fieldAttrib('size', 30)
        
    ->addField('text', 'price')
        ->fieldLabel('Price per hour')
        ->fieldRequired()
        ->fieldAttrib('maxlength', 10)
        ->fieldAttrib('size', 10)

    ->addField('submit')
        ->fieldAction($this->supplier, 'createRole')
    ?>