<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
 * @version $Id$
-->
 
<?=$this->publish($this->project->deliverables)?>

<? $this->includeCSS('pages/projects/_any/Scope/Coverage/matrix.css') ?>

<h1>Traceability Coverage</h1>

<? $options = array(
    'requirements',
    'design',
    'classes',
    'functional',
    'issues',
    'all',
) ?>

<?=$this->forma('coverage')
    ->addAttrib('class', 'inline')
    ->addBehavior('nothing')
    ->addField('select', 'from')
        ->fieldOptions($options)
        ->fieldUseValues(true)
        ->fieldLabel('From')
    ->addField('select', 'to')
        ->fieldOptions($options)
        ->fieldUseValues(true)
        ->fieldLabel('To')
    ->addField('submit', 'submit')
        ->fieldValue('Refresh')
        ->fieldAttrib('class', 'btn')
    ?>
  
<? if ($this->forma('coverage')->isCompleted()): ?>
    <div class="matrix">  
    <?
        $from = $this->forma('coverage')->getParam('from');
        $to = $this->forma('coverage')->getParam('to');

        $dest = $this->project->deliverables->$to;
        $source = $this->project->deliverables->$from;

        $matrix = $this->project->traceability->getCoverageMatrix($source, $dest);
        
        foreach ($dest as $id=>$deliverable) {
            $classes = $titles = array();
            if (!$deliverable->wasAccepted()) {
                $classes[] = 'draft';
            }
            if ($deliverable->outOfScope) {
                $classes[] = 'out';
                $titles[] = 'out of scope';
            }
            if (!empty($matrix[$id])) {
                $classes[] = 'covered';
                $titles[] = 'by ' . $matrix[$id];
            }
            echo sprintf(
                "<span%s%s>%s</span>\n",
                !empty($classes) ? ' class="' . implode(' ', $classes) . '"' : false,
                !empty($titles) ? ' title="' . implode('; ', $titles) . '"' : false,
                $deliverable->name
            );
        }
    ?>
    </div>  
    
    <p>Coverage: 
        <b><?=round($this->project->traceability->getCoverage($source, $dest) * 100, 2)?>%</b>,
        <?=count($dest)?> elements to be covered by <?=count($source)?> sources.</p>
<? endif; ?>

