<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
 * @version $Id$
-->
 
<? $this->includeCSS('pages/projects/_any/Scope/DesignModel/tree.css') ?>

<?=$this->publish($this->project->deliverables)?>

<h1>Design Model</h1>

<?=$this->bar()
    ->addLink('Classes', 'Classes')
    ->addLink('Files', 'Files')
    ->addLink('TestCases', 'Test Cases')
    ?>

<?=$this->tree()
    ->setCollection($this->project->deliverables->design, 'name', '.')
    ->setOptions(
        array(
            // 'renderSections' => false,
            'startCollapsed' => true,
        )
    )
    ->addAttrib('class', 'tree')
    ->setMask(
        'sprintf(
            "<span class=\'node\'>%s</span> (%s)",
            ${a1}->name,
            ${a1}->type
        )'
    )
    ?>
