<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
 * @version $Id$
-->
 
<?=$this->publish($this->project->deliverables)?>

<h1>Traceability Matrix</h1>

<p>There are <?=count($this->project->traceability)?>
    traceability links:</p>

<?
    $bar = $this->bar()->setStyle('stairs');
    foreach ($this->project->traceability->getAllSourceTypes() as $type) {
        $bar->addLink(
            $type, 
            sprintf(
                '%s(s) trace to..., %d links',
                $type,
                count($this->project->traceability->getSourcesByType($type))
            )
        );
    }
?>

<?=$bar?>
