<!--
 *
 * thePanel v2.0, Project Management Software Toolkit
 *
 * Redistribution and use in source and binary forms, with or without 
 * modification, are PROHIBITED without prior written permission from 
 * the author. This product may NOT be used anywhere and on any computer 
 * except the server platform of TechnoPark Corp. located at 
 * www.technoparkcorp.com. If you received this code occasionally and 
 * without intent to use it, please report this incident to the author 
 * by email: privacy@technoparkcorp.com or by mail: 
 * 568 Ninth Street South 202, Naples, Florida 34102, USA
 * tel. +1 (239) 935 5429
 *
 * @version $Id$
-->
 
<?=$this->publish($this->project->wbs)?>

<h1>Work Breakdown Structure (WBS)</h1>

<?=$this->table()
    // ->setSource($this->project->wbs)
    ->setSource($this->project->wbs->getWorkPackagesByPrefix(''))
    ->addColumn('code', 'Work package')
    ->addColumn('cost', 'Cost')
    ->addColumn('title', 'Statement of work')

    ->addOption('code', '{code}')
    ?>
    
<p>Total Cost: <b><?=$this->project->wbs->sum()?></b></p>

<?=$this->tree()
    ->setCollection($this->project->wbs, 'code', '/')
    ->setOptions(
        array(
            'suffixOnly' => true,
        )
    )
    ->addAttrib('class', 'tree')
    ->setMask(
        'sprintf(
            "<tt title=\'%s\'>%s</tt>: %s",
            ${a1}->code,
            ${a1}->cost,
            ${a1}->title
        )')
    ?>
